import '../../../shared/styles/color_style.dart';

final List<Map<String, dynamic>> taskData = [
  {
    'title': 'Team Meeting',
    'description':
        'Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps',
    'time': '10:00 AM',
    'color': ColorStyle.primary,
    'date': 'Nov 20, 2023',
    'isPin': false,
  },
  {
    'title': 'Design Review',
    'description':
        'Discuss project updates and next steps Discuss project updates and next steps',
    'time': '11:30 AM',
    'color': ColorStyle.accent,
    'date': 'Nov 20, 2023',
    'isPin': false,
  },
  {
    'title': 'Lunch Break',
    'description':
        'Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps',
    'time': '01:00 PM',
    'color': ColorStyle.secondary,
    'date': 'Nov 20, 2023',
    'isPin': false,
  },
  {
    'title': 'Client Call',
    'description': 'Discuss project updates and next steps',
    'time': '02:30 PM',
    'color': ColorStyle.dark,
    'date': 'Nov 20, 2023',
    'isPin': false,
  },
  {
    'title': 'Coding Session',
    'description': 'Discuss project updates and next steps',
    'time': '04:00 PM',
    'color': ColorStyle.grey,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Daily Report',
    'description': 'Discuss project updates and next steps',
    'time': '05:30 PM',
    'color': ColorStyle.primary,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Coding Session',
    'description': 'Discuss project updates and next steps',
    'time': '04:00 PM',
    'color': ColorStyle.secondary,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Daily Report',
    'description': 'Discuss project updates and next steps',
    'time': '05:30 PM',
    'color': ColorStyle.accent,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Coding Session',
    'description': 'Discuss project updates and next steps',
    'time': '04:00 PM',
    'color': ColorStyle.grey,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Daily Report',
    'description': 'Discuss project updates and next steps',
    'time': '05:30 PM',
    'color': ColorStyle.primary,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Coding Session',
    'description': 'Discuss project updates and next steps',
    'time': '04:00 PM',
    'color': ColorStyle.secondary,
    'date': 'Nov 21, 2023',
    'isPin': false,
  },
  {
    'title': 'Team Meeting',
    'description': 'Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps',
    'time': '10:00 AM',
    'color': ColorStyle.primary,
    'date': 'May 22, 2025',
    'isPin': true,
  },
  {
    'title': 'Daily Report',
    'description': 'Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps',
    'time': '05:30 PM',
    'color': ColorStyle.accent,
    'date': 'Nov 21, 2023',
    'isPin': true,
  },
  {
    'title': 'Design Review',
    'description': 'UI feedback and Figma updates Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps Discuss project updates and next steps',
    'time': '11:30 AM',
    'color': ColorStyle.grey,
    'date': 'May 22, 2025',
    'isPin': false,
  },
  {
    'title': 'Lunch Break',
    'description': 'Recharge and relax',
    'time': '01:00 PM',
    'color': ColorStyle.secondary,
    'date': 'May 22, 2025',
    'isPin': true,
  },
  {
    'title': 'Code Review',
    'description': 'Review merge requests',
    'time': '03:00 PM',
    'color': ColorStyle.grey,
    'date': 'May 22, 2025',
    'isPin': false,
  },
  {
    'title': 'Daily Report',
    'description': 'Fill out project tracker',
    'time': '05:30 PM',
    'color': ColorStyle.primary,
    'date': 'May 22, 2025',
    'isPin': false,
  },
  {
    'title': 'Team Sync',
    'description': 'Align on sprint goals',
    'time': '09:00 AM',
    'color': ColorStyle.dark,
    'date': 'May 23, 2025',
    'isPin': false,
  },
  {
    'title': 'Client Call',
    'description': 'Product demo and feedback',
    'time': '02:00 PM',
    'color': ColorStyle.secondary,
    'date': 'May 23, 2025',
    'isPin': false,
  },
  {
    'title': 'Design Sprint',
    'description': 'Work on new feature UI',
    'time': '04:00 PM',
    'color': ColorStyle.accent,
    'date': 'May 24, 2025',
    'isPin': false,
  },
];
