const Map<String, String> idID = {
  'locale': 'id_ID',
  'Email': 'Email',
  'Phone': 'Nomor Telepon',
  'Birthday': 'Tanggal Lahir',
  'Password': 'Kata Sandi',
  'Language': 'Bahasa',
  'Help & Support': 'Bantuan & Dukungan',
  'Change Language': 'Ganti Bahasa',
  'Bahasa Indonesia': 'Bahasa Indonesia',
  'English': 'Inggris',
  'Indonesia': 'Indonesia',
  '🇮🇩': '🇮🇩',
  '🇬🇧': '🇬🇧',
  'Profile': 'Profil',
  'Help center, contact us & privacy policy':
      'Pusat Bantuan, Hubungi Kami & Kebijakan Privasi',
  'Task': 'Tugas',
  'Note': 'Catatan',
  'About': 'Tentang',
  'Logout': 'Keluar',
  'Search': 'Cari',
  'Hidden': 'Tersembunyi',

  'Search tasks': 'Cari tugas',
  'Search notes': 'Cari catatan',
  'About Me': 'Tentang Saya',
  'Change Password': 'Ganti Kata Sandi',
  'Change Pin': 'Ganti PIN',
  'Set Pin': 'Atur PIN',
  'Address': 'Alamat',
  'Address not set': 'Alamat tidak diatur',
  'Our Social Media': 'Media Sosial Kami',
};
