const Map<String, String> enUS = {
  'locale': 'en_US',
  'Email': 'Email',
  'Phone': 'Phone',
  'Birthday': 'Birthday',
  'Password': 'Password',
  'Language': 'Language',
  'Help & Support': 'Help & Support',
  'Change Language': 'Change Language',
  'Bahasa Indonesia': 'Indonesian',
  'English': 'English',
  'Indonesia': 'Indonesia',
  '🇮🇩': '🇮🇩',
  '🇬🇧': '🇬🇧',
  'Profile': 'Profile',
  'Help center, contact us & privacy policy':
      'Help center, contact us & privacy policy',
  'Task': 'Task',
  'Note': 'Note',
  'About': 'About',
  'Logout': 'Logout',
  'Search': 'Search',
  'Hidden': 'Hidden',

  'Search tasks': 'Search tasks',
  'Search notes': 'Search notes',
  'About Me': 'About Me',
  'Change Password': 'Change Password',
  'Change Pin': 'Change Pin',
  'Set Pin': 'Set Pin',
  'Address': 'Address',
  'Address not set': 'Address not set',
  'Our Social Media': 'Our Social Media',
};
