// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:voice_task/features/landing/models/user_model.dart';
import 'package:voice_task/features/note/sub_features/add_note/models/note_model.dart';
import 'package:voice_task/features/task/models/task_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(NoteAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(TaskStatusAdapter());
    registerAdapter(UserModelAdapter());
  }
}
